server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

logging:
  level:
    root: INFO
    com.ordermanagement.api_gateway: DEBUG
    org.springframework.cloud.gateway: INFO
